spring:
  application:
    name: restory
  profiles:
    active: ${profile}
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: 80
  servlet:
    encoding:
      force-response: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


