server:
  port: 80
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: restory
  profiles:
    active: ${profile}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: true


