spring:
  application:
    name: restory
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: true
#    security:
#      oauth2:
#        client:
#          registration:
#            kakao:
#              client-id: 앱 설정 -> 앱 키 -> REST API 키
#              client-secret: 제품 설정 -> 카카오 로그인 -> 보안 -> Client Secret
#              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#              authorization-grant-type: authorization_code
#              client-authentication-method: POST
#              scope:
#                - profile_nickname
#                - profile_image
#          provider:
#            kakao:
#            # 카카오의 기본 URL을 사용하여 생략할 수 있습니다
#            # authorization-uri, token-uri, user-info-uri 등을 기본값으로 설정
server:
  servlet:
    session:
      cookie:
        path: /
        http-only: true
        secure: true

springdoc:
  packages-to-scan: com.cw.restory.web
  default-consumes-media-type: application/json;
  default-produces-media-type: application/json;
  show-actuator: true
  swagger-ui:
    path: /api/docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    default-model-expand-depth: 2



